# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm install
            - name: Check commit message
              run: |
                  if [[ "${{ github.event.head_commit.message }}" == *"generate root pem"* ]]; then
                    echo "Commit message contains the keyword."
                    # Perform additional actions or steps here
                    node genrate.js
                  else
                    echo "Commit message does not contain the keyword."
                    # Perform other actions or steps here
                  fi